"""Layout MXF (MiTek Exchange XML) builder.

Consumes a ``DesignParameters``-like object and emits a Pamir-compatible Layout
MXF document describing the four outer building walls together with the roof
and floor surfaces.

All coordinates are written in metres and the building is placed at local origin
``(0, 0, 0)``. The four walls run clockwise around the floor-plan rectangle and
each wall's thickness (Z) axis points inward so the perimeter matches the
standard Pamir import convention. Roof planes and the floor are emitted as
``<RoofList>`` / ``<FloorList>`` (under ``<Building>``) plus a root-level
``<SurfaceList>`` so Pamir imports the intended roof shape and pitch.
"""

import math
import xml.etree.ElementTree as ET
from typing import Any
from xml.dom import minidom

try:
    from src.geometry_solver import (
        GeometrySolver,
        floor_surface_polygon,
        parse_dimensions,
        parse_overhang,
        roof_surface_polygons,
    )
except ImportError:  # pragma: no cover - direct module import in unit tests
    from geometry_solver import (  # type: ignore[no-redef,import-not-found]
        GeometrySolver,
        floor_surface_polygon,
        parse_dimensions,
        parse_overhang,
        roof_surface_polygons,
    )

# Wall thickness and skin height in metres. These mirror the Pamir reference
# export (``hidden/Sample_Project/Test Project 2.mxf``) so generated layouts
# import cleanly without rescaling.
WALL_THICKNESS = 0.2
WALL_HEIGHT = 3.0

# Wall plate geometry in metres (offset/height/width) attached to every outer
# wall. Matches the standard Pamir export for the default skin thickness.
WALL_PLATE_OFFSET = 0.05
WALL_PLATE_HEIGHT = 0.05
WALL_PLATE_WIDTH = 0.1

# Full-span gable common-truss frame geometry (metres). Mirrors the Pamir
# reference export (``hidden/Sample_Project/7JULY_Z.mxf``) so generated frames
# import cleanly into MiTek Pamir as wall-to-wall trusses instead of the
# split half-span auto-framing produced by layout-only roof surfaces.
MEMBER_OVERALL_THICKNESS = 0.045
MEMBER_ORIENTATION = "edgewise"
# Timber section ID referenced by every common-truss WoodMember. The matching
# ``<TimberSectionList>`` definition is emitted by a later task; the ID is
# kept stable from this point so downstream tasks can reference it.
COMMON_TRUSS_TIMBER_ID = "TS2"
# Frame family / type / status for a standard full-span gable common truss.
COMMON_TRUSS_FAMILY = "Truss"
COMMON_TRUSS_FRAME_TYPE = "roof"
COMMON_TRUSS_FRAME_STATUS = "designed ok"
# Part / ply naming for the single-piece (non-transport-split) common truss.
COMMON_TRUSS_PART_NAME = "Part 1"
COMMON_TRUSS_PLY = "1"

MXF_VERSION = "MXF Version 5.11"
MXF_COMMENT = "Layout MXF generated by dkp-demo agent"
MXF_ORIGINATOR = "dkp-demo agent"

XSD_NS = "http://www.w3.org/2001/XMLSchema"
XSI_NS = "http://www.w3.org/2001/XMLSchema-instance"


def _format_point(*coords: float) -> str:
    """Render a coordinate tuple as a comma-separated MXF point string.

    ``c + 0.0`` normalizes negative zero (e.g. from ``-0.0`` overhangs) to
    ``0`` so coordinate strings stay clean for Pamir to parse.
    """
    return ",".join(f"{c + 0.0:g}" for c in coords)


def _face_polygon(start: float, end: float) -> str:
    """Build a 2D skin ``polygon`` (``x,height`` pairs) spanning x in [start, end]."""
    h = WALL_HEIGHT
    return (
        f"{start:g},0 {end:g},0 {end:g},{h:g} {start:g},{h:g}"
    )


def wall_specs(width_m: float, depth_m: float) -> list[dict[str, Any]]:
    """Return geometry for the four outer walls, clockwise from the bottom (Y=0).

    Each wall carries:
      - ``id``: the wall identifier (``W0``..``W3``)
      - ``origin``: wall start corner, as an ``(x, y, z)`` tuple
      - ``x_axis``: running-axis point (``origin`` + east/north/west/south unit)
      - ``y_axis``: vertical-axis point (``origin`` + up unit)
      - ``z_axis``: inward thickness-axis point (``origin`` + inward unit)
      - ``length``: wall run length in metres

    The running axis of each wall points at the next wall's origin, so the four
    walls trace a closed rectangle. The thickness axis always points toward the
    building centre.
    """
    w, d = width_m, depth_m
    # (id, origin, running direction, inward thickness direction) per wall.
    base = [
        ("W0", (0.0, 0.0, 0.0), (1.0, 0.0, 0.0), (0.0, 1.0, 0.0)),
        ("W1", (w,   0.0, 0.0), (0.0, 1.0, 0.0), (-1.0, 0.0, 0.0)),
        ("W2", (w,   d,   0.0), (-1.0, 0.0, 0.0), (0.0, -1.0, 0.0)),
        ("W3", (0.0, d,   0.0), (0.0, -1.0, 0.0), (1.0, 0.0, 0.0)),
    ]
    definitions: list[dict[str, Any]] = []
    for index, (wall_id, origin, run, inward) in enumerate(base):
        ox, oy, oz = origin
        rx, ry, rz = run
        ix, iy, iz = inward
        spec: dict[str, Any] = {
            "id": wall_id,
            "origin": origin,
            "run": run,
            "inward": inward,
            "x_axis": (ox + rx, oy + ry, oz + rz),
            "y_axis": (ox, oy, oz + 1.0),
            "z_axis": (ox + ix, oy + iy, oz + iz),
            # W0/W2 run along the width; W1/W3 run along the depth.
            "length": width_m if index in (0, 2) else depth_m,
        }
        definitions.append(spec)
    return definitions


def _validate_plan(width_m: float, depth_m: float) -> None:
    if width_m <= 0 or depth_m <= 0:
        raise ValueError(
            f"floorPlanDimensions must be positive and non-zero (got {width_m}x{depth_m})"
        )


def _build_building_walls(parent: ET.Element, specs: list[dict[str, Any]]) -> None:
    wall_list = ET.SubElement(parent, "BuildingWallList")
    for spec in specs:
        wall = ET.SubElement(wall_list, "BuildingWall", {"wall_ID": spec["id"]})
        ET.SubElement(
            wall,
            "Position",
            {
                "origin": _format_point(*spec["origin"]),
                "xAxis": _format_point(*spec["x_axis"]),
                "yAxis": _format_point(*spec["y_axis"]),
                "zAxis": _format_point(*spec["z_axis"]),
            },
        )


def _build_walls(parent: ET.Element, specs: list[dict[str, Any]]) -> None:
    wall_list = ET.SubElement(parent, "WallList")
    for spec in specs:
        wall = ET.SubElement(
            wall_list,
            "Wall",
            {
                "id": spec["id"],
                "overallThickness": f"{WALL_THICKNESS:g}",
                "type": "Outer",
                "usageType": "external",
            },
        )
        skin_list = ET.SubElement(wall, "SkinList")
        skin = ET.SubElement(
            skin_list,
            "Skin",
            {"thickness": f"{WALL_THICKNESS:g}", "id": f"{spec['id']}_S0"},
        )
        front_face = ET.SubElement(skin, "FrontFace")
        ET.SubElement(
            front_face,
            "Face",
            {
                "lowerStart": "1",
                "lowerEnd": "2",
                "polygon": _face_polygon(0.0, spec["length"]),
                "upperStart": "3",
                "upperEnd": "4",
                "z": "0",
            },
        )
        back_face = ET.SubElement(skin, "BackFace")
        ET.SubElement(
            back_face,
            "Face",
            {
                "lowerStart": "1",
                "lowerEnd": "2",
                "polygon": _face_polygon(WALL_THICKNESS, spec["length"] - WALL_THICKNESS),
                "upperStart": "3",
                "upperEnd": "4",
                "z": f"{WALL_THICKNESS:g}",
            },
        )

        plate_list = ET.SubElement(wall, "WallPlateList")
        ET.SubElement(
            plate_list,
            "WallPlate",
            {
                "offset": f"{WALL_PLATE_OFFSET:g}",
                "height": f"{WALL_PLATE_HEIGHT:g}",
                "width": f"{WALL_PLATE_WIDTH:g}",
            },
        )


def _build_metadata(parent: ET.Element, batch_name: str) -> None:
    job_list = ET.SubElement(parent, "JobList")
    job = ET.SubElement(
        job_list,
        "Job",
        {"customerID": "C0", "name": batch_name, "description": batch_name},
    )
    ET.SubElement(job, "Author", {"name": "DefaultUser"})

    customer_list = ET.SubElement(parent, "CustomerList")
    ET.SubElement(
        customer_list,
        "Customer",
        {"id": "C0", "name": "SlovakRepublic", "contact": "DefaultUser"},
    )


def _format_polygon(points: list[tuple[float, float, float]]) -> str:
    """Render a list of ``(x, y, z)`` points as an MXF ``polygon`` attribute."""
    return " ".join(_format_point(x, y, z) for x, y, z in points)


def _resolve_roof_key(params: Any) -> str:
    raw = getattr(params, "roofType", None)
    return (raw or "flat").strip().lower()


def _resolve_overhang_m(params: Any) -> float:
    """Resolve the overhang in metres, defaulting to 0 when unset/unparseable."""
    mm = parse_overhang(getattr(params, "overhang", None))
    return (mm or 0.0) / 1000.0


def _resolve_pitch(params: Any) -> float:
    raw = getattr(params, "roofPitch", None)
    return float(raw) if raw is not None else 0.0


def _build_surfaces(
    root: ET.Element,
    building: ET.Element,
    floor_points: list[tuple[float, float, float]],
    roof_polygons: list[list[tuple[float, float, float]]],
) -> None:
    """Emit ``<RoofList>``/``<FloorList>`` under ``<Building>`` and the root
    ``<SurfaceList>`` mapping roof surface IDs ``SR0-*`` and floor ``SF0-0``."""
    roof_list = ET.SubElement(building, "RoofList")
    for index in range(len(roof_polygons)):
        ET.SubElement(roof_list, "Roof", {"surfaceID": f"SR0-{index}"})

    floor_list = ET.SubElement(building, "FloorList")
    ET.SubElement(floor_list, "Floor", {"surfaceID": "SF0-0"})

    surface_list = ET.SubElement(root, "SurfaceList")
    for index, polygon in enumerate(roof_polygons):
        ET.SubElement(
            surface_list,
            "Surface",
            {
                "id": f"SR0-{index}",
                "polygon": _format_polygon(polygon),
                "covering": "undefined",
            },
        )
    ET.SubElement(
        surface_list,
        "Surface",
        {
            "id": "SF0-0",
            "polygon": _format_polygon(floor_points),
            "verticalOffset": "0",
        },
    )


def _chord_length(
    start: tuple[float, float], end: tuple[float, float]
) -> float:
    """Euclidean length of a 2D chord segment (metres)."""
    dx, dy = end[0] - start[0], end[1] - start[1]
    return math.sqrt(dx * dx + dy * dy)


def _member_face_polygon(
    start: tuple[float, float], end: tuple[float, float], thickness: float
) -> str:
    """Render a WoodMember Face polygon (local ``x,y`` pairs) as a thin rectangle.

    The structural chord line runs from ``start`` to ``end`` (the first two
    polygon points); the rectangle extends ``thickness`` metres perpendicular
    to the chord toward the lower/outside face so the polygon keeps the
    four-point shape used by the Pamir reference export.
    """
    x1, y1 = start
    x2, y2 = end
    dx, dy = x2 - x1, y2 - y1
    length = math.sqrt(dx * dx + dy * dy) or 1e-9
    # Clockwise perpendicular: for a left-to-right chord this points downward
    # (outside the roof envelope), matching the reference bottom-chord layout.
    ox = (dy / length) * thickness
    oy = -(dx / length) * thickness
    return (
        f"{x1 + 0.0:g},{y1 + 0.0:g} "
        f"{x2 + 0.0:g},{y2 + 0.0:g} "
        f"{(x2 + ox) + 0.0:g},{(y2 + oy) + 0.0:g} "
        f"{(x1 + ox) + 0.0:g},{(y1 + oy) + 0.0:g}"
    )


def _build_frame_list(
    root: ET.Element,
    solver: GeometrySolver,
    overhang_m: float,
    batch_name: str,
) -> None:
    """Emit ``<FrameList>`` with full-span gable common-truss chord members.

    For gable roofs a single ``<Frame family="Truss">`` definition carries the
    full-span chord layout (two TopChords meeting at the central ridge plus one
    wall-to-wall BottomChord) shared by every common truss; ``quantity``
    records how many instances are placed along the depth axis. MiTek Pamir
    imports this as a single wall-to-wall truss per row instead of auto-framing
    each roof half into split half-spans. Non-gable roofs emit no FrameList.
    """
    frames = solver.mxf_truss_frames(overhang_m)
    if not frames:
        return

    # Every common truss shares the same LOCAL chord geometry; only the Y
    # position along the building depth differs. Emit one reusable Frame
    # definition whose ``quantity`` reflects the truss count.
    _, members = frames[0]
    count = len(frames)

    frame_list = ET.SubElement(root, "FrameList")
    frame = ET.SubElement(
        frame_list,
        "Frame",
        {
            "cambered": "false",
            "family": COMMON_TRUSS_FAMILY,
            "id": "F0",
            "job": batch_name,
            "modified": "Initial",
            "name": "S1",
            "ply": COMMON_TRUSS_PLY,
            "quantity": str(count),
            "quantityWithPly": str(count),
            "status": COMMON_TRUSS_FRAME_STATUS,
            "type": COMMON_TRUSS_FRAME_TYPE,
        },
    )
    part_list = ET.SubElement(frame, "PartList")
    part = ET.SubElement(
        part_list, "Part", {"name": COMMON_TRUSS_PART_NAME, "ply": COMMON_TRUSS_PLY}
    )
    member_list = ET.SubElement(part, "MemberList")
    for index, (member_type, start, end) in enumerate(members):
        wood_member = ET.SubElement(
            member_list,
            "WoodMember",
            {
                "name": f"Member {index + 1}",
                "overallThickness": f"{MEMBER_OVERALL_THICKNESS:g}",
                "ply": COMMON_TRUSS_PLY,
                "stockLength": f"{_chord_length(start, end):g}",
                "timberID": COMMON_TRUSS_TIMBER_ID,
                "type": member_type,
                "id": f"M0-0-{index}",
                "orientation": MEMBER_ORIENTATION,
            },
        )
        front_face = ET.SubElement(wood_member, "FrontFace")
        ET.SubElement(
            front_face,
            "Face",
            {
                "lowerStart": "1",
                "lowerEnd": "2",
                "polygon": _member_face_polygon(
                    start, end, MEMBER_OVERALL_THICKNESS
                ),
                "upperStart": "3",
                "upperEnd": "4",
                "z": "0",
            },
        )


def build_mxf(params: Any) -> bytes:
    """Generate a Layout MXF document (UTF-8 bytes) from ``DesignParameters``.

    Raises ``ValueError`` when ``floorPlanDimensions`` is missing, malformed,
    or non-positive.
    """
    width_mm, depth_mm = parse_dimensions(getattr(params, "floorPlanDimensions", None))
    width_m = width_mm / 1000.0
    depth_m = depth_mm / 1000.0
    _validate_plan(width_m, depth_m)

    specs = wall_specs(width_m, depth_m)
    batch_name = getattr(params, "buildingType", None) or "Building"

    roof_key = _resolve_roof_key(params)
    pitch_deg = _resolve_pitch(params)
    overhang_m = _resolve_overhang_m(params)
    roof_polygons = roof_surface_polygons(roof_key, width_m, depth_m, pitch_deg, overhang_m)
    floor_points = floor_surface_polygon(width_m, depth_m)

    solver = GeometrySolver(width_mm, depth_mm, roof_key, pitch_deg)

    root = ET.Element("Mxf")
    root.set("xmlns:xsd", XSD_NS)
    root.set("xmlns:xsi", XSI_NS)
    root.set("comment", MXF_COMMENT)
    root.set("originator", MXF_ORIGINATOR)
    root.set("version", MXF_VERSION)
    root.set("batchName", batch_name)
    root.set("batchDescription", batch_name)

    building_list = ET.SubElement(root, "BuildingList")
    building = ET.SubElement(
        building_list, "Building", {"job": batch_name, "name": batch_name}
    )
    _build_building_walls(building, specs)
    _build_walls(root, specs)
    _build_surfaces(root, building, floor_points, roof_polygons)
    _build_frame_list(root, solver, overhang_m, batch_name)
    _build_metadata(root, batch_name)

    raw = ET.tostring(root, encoding="utf-8")
    return minidom.parseString(raw).toprettyxml(indent="  ", encoding="utf-8")
