"""Layout MXF (MiTek Exchange XML) builder.

Consumes a ``DesignParameters``-like object and emits a Pamir-compatible Layout
MXF document describing the four outer building walls together with the roof
and floor surfaces.

All coordinates are written in metres and the building is placed at local origin
``(0, 0, 0)``. The four walls run clockwise around the floor-plan rectangle and
each wall's thickness (Z) axis points inward so the perimeter matches the
standard Pamir import convention. Roof planes and the floor are emitted as
``<RoofList>`` / ``<FloorList>`` (under ``<Building>``) plus a root-level
``<SurfaceList>`` so Pamir imports the intended roof shape and pitch.
"""

import xml.etree.ElementTree as ET
from typing import Any
from xml.dom import minidom

try:
    from src.geometry_solver import (
        floor_surface_polygon,
        parse_dimensions,
        parse_overhang,
        roof_surface_polygons,
    )
except ImportError:  # pragma: no cover - direct module import in unit tests
    from geometry_solver import (  # type: ignore[no-redef,import-not-found]
        floor_surface_polygon,
        parse_dimensions,
        parse_overhang,
        roof_surface_polygons,
    )

# Wall thickness and skin height in metres. These mirror the Pamir reference
# export (``hidden/Sample_Project/Test Project 2.mxf``) so generated layouts
# import cleanly without rescaling.
WALL_THICKNESS = 0.2
WALL_HEIGHT = 3.0

# Wall plate geometry in metres (offset/height/width) attached to every outer
# wall. Matches the standard Pamir export for the default skin thickness.
WALL_PLATE_OFFSET = 0.05
WALL_PLATE_HEIGHT = 0.05
WALL_PLATE_WIDTH = 0.1

MXF_VERSION = "MXF Version 5.11"
MXF_COMMENT = "Layout MXF generated by dkp-demo agent"
MXF_ORIGINATOR = "dkp-demo agent"

XSD_NS = "http://www.w3.org/2001/XMLSchema"
XSI_NS = "http://www.w3.org/2001/XMLSchema-instance"


def _format_point(*coords: float) -> str:
    """Render a coordinate tuple as a comma-separated MXF point string.

    ``c + 0.0`` normalizes negative zero (e.g. from ``-0.0`` overhangs) to
    ``0`` so coordinate strings stay clean for Pamir to parse.
    """
    return ",".join(f"{c + 0.0:g}" for c in coords)


def _face_polygon(start: float, end: float) -> str:
    """Build a 2D skin ``polygon`` (``x,height`` pairs) spanning x in [start, end]."""
    h = WALL_HEIGHT
    return (
        f"{start:g},0 {end:g},0 {end:g},{h:g} {start:g},{h:g}"
    )


def wall_specs(width_m: float, depth_m: float) -> list[dict[str, Any]]:
    """Return geometry for the four outer walls, clockwise from the bottom (Y=0).

    Each wall carries:
      - ``id``: the wall identifier (``W0``..``W3``)
      - ``origin``: wall start corner, as an ``(x, y, z)`` tuple
      - ``x_axis``: running-axis point (``origin`` + east/north/west/south unit)
      - ``y_axis``: vertical-axis point (``origin`` + up unit)
      - ``z_axis``: inward thickness-axis point (``origin`` + inward unit)
      - ``length``: wall run length in metres

    The running axis of each wall points at the next wall's origin, so the four
    walls trace a closed rectangle. The thickness axis always points toward the
    building centre.
    """
    w, d = width_m, depth_m
    # (id, origin, running direction, inward thickness direction) per wall.
    base = [
        ("W0", (0.0, 0.0, 0.0), (1.0, 0.0, 0.0), (0.0, 1.0, 0.0)),
        ("W1", (w,   0.0, 0.0), (0.0, 1.0, 0.0), (-1.0, 0.0, 0.0)),
        ("W2", (w,   d,   0.0), (-1.0, 0.0, 0.0), (0.0, -1.0, 0.0)),
        ("W3", (0.0, d,   0.0), (0.0, -1.0, 0.0), (1.0, 0.0, 0.0)),
    ]
    definitions: list[dict[str, Any]] = []
    for index, (wall_id, origin, run, inward) in enumerate(base):
        ox, oy, oz = origin
        rx, ry, rz = run
        ix, iy, iz = inward
        spec: dict[str, Any] = {
            "id": wall_id,
            "origin": origin,
            "run": run,
            "inward": inward,
            "x_axis": (ox + rx, oy + ry, oz + rz),
            "y_axis": (ox, oy, oz + 1.0),
            "z_axis": (ox + ix, oy + iy, oz + iz),
            # W0/W2 run along the width; W1/W3 run along the depth.
            "length": width_m if index in (0, 2) else depth_m,
        }
        definitions.append(spec)
    return definitions


def _validate_plan(width_m: float, depth_m: float) -> None:
    if width_m <= 0 or depth_m <= 0:
        raise ValueError(
            f"floorPlanDimensions must be positive and non-zero (got {width_m}x{depth_m})"
        )


def _build_building_walls(parent: ET.Element, specs: list[dict[str, Any]]) -> None:
    wall_list = ET.SubElement(parent, "BuildingWallList")
    for spec in specs:
        wall = ET.SubElement(wall_list, "BuildingWall", {"wall_ID": spec["id"]})
        ET.SubElement(
            wall,
            "Position",
            {
                "origin": _format_point(*spec["origin"]),
                "xAxis": _format_point(*spec["x_axis"]),
                "yAxis": _format_point(*spec["y_axis"]),
                "zAxis": _format_point(*spec["z_axis"]),
            },
        )


def _build_walls(parent: ET.Element, specs: list[dict[str, Any]]) -> None:
    wall_list = ET.SubElement(parent, "WallList")
    for spec in specs:
        wall = ET.SubElement(
            wall_list,
            "Wall",
            {
                "id": spec["id"],
                "overallThickness": f"{WALL_THICKNESS:g}",
                "type": "Outer",
                "usageType": "external",
            },
        )
        skin_list = ET.SubElement(wall, "SkinList")
        skin = ET.SubElement(
            skin_list,
            "Skin",
            {"thickness": f"{WALL_THICKNESS:g}", "id": f"{spec['id']}_S0"},
        )
        front_face = ET.SubElement(skin, "FrontFace")
        ET.SubElement(
            front_face,
            "Face",
            {
                "lowerStart": "1",
                "lowerEnd": "2",
                "polygon": _face_polygon(0.0, spec["length"]),
                "upperStart": "3",
                "upperEnd": "4",
                "z": "0",
            },
        )
        back_face = ET.SubElement(skin, "BackFace")
        ET.SubElement(
            back_face,
            "Face",
            {
                "lowerStart": "1",
                "lowerEnd": "2",
                "polygon": _face_polygon(WALL_THICKNESS, spec["length"] - WALL_THICKNESS),
                "upperStart": "3",
                "upperEnd": "4",
                "z": f"{WALL_THICKNESS:g}",
            },
        )

        plate_list = ET.SubElement(wall, "WallPlateList")
        ET.SubElement(
            plate_list,
            "WallPlate",
            {
                "offset": f"{WALL_PLATE_OFFSET:g}",
                "height": f"{WALL_PLATE_HEIGHT:g}",
                "width": f"{WALL_PLATE_WIDTH:g}",
            },
        )


def _build_metadata(parent: ET.Element, batch_name: str) -> None:
    job_list = ET.SubElement(parent, "JobList")
    job = ET.SubElement(
        job_list,
        "Job",
        {"customerID": "C0", "name": batch_name, "description": batch_name},
    )
    ET.SubElement(job, "Author", {"name": "DefaultUser"})

    customer_list = ET.SubElement(parent, "CustomerList")
    ET.SubElement(
        customer_list,
        "Customer",
        {"id": "C0", "name": "SlovakRepublic", "contact": "DefaultUser"},
    )


def _format_polygon(points: list[tuple[float, float, float]]) -> str:
    """Render a list of ``(x, y, z)`` points as an MXF ``polygon`` attribute."""
    return " ".join(_format_point(x, y, z) for x, y, z in points)


def _resolve_roof_key(params: Any) -> str:
    raw = getattr(params, "roofType", None)
    return (raw or "flat").strip().lower()


def _resolve_overhang_m(params: Any) -> float:
    """Resolve the overhang in metres, defaulting to 0 when unset/unparseable."""
    mm = parse_overhang(getattr(params, "overhang", None))
    return (mm or 0.0) / 1000.0


def _resolve_pitch(params: Any) -> float:
    raw = getattr(params, "roofPitch", None)
    return float(raw) if raw is not None else 0.0


def _build_surfaces(
    root: ET.Element,
    building: ET.Element,
    floor_points: list[tuple[float, float, float]],
    roof_polygons: list[list[tuple[float, float, float]]],
) -> None:
    """Emit ``<RoofList>``/``<FloorList>`` under ``<Building>`` and the root
    ``<SurfaceList>`` mapping roof surface IDs ``SR0-*`` and floor ``SF0-0``."""
    roof_list = ET.SubElement(building, "RoofList")
    for index in range(len(roof_polygons)):
        ET.SubElement(roof_list, "Roof", {"surfaceID": f"SR0-{index}"})

    floor_list = ET.SubElement(building, "FloorList")
    ET.SubElement(floor_list, "Floor", {"surfaceID": "SF0-0"})

    surface_list = ET.SubElement(root, "SurfaceList")
    for index, polygon in enumerate(roof_polygons):
        ET.SubElement(
            surface_list,
            "Surface",
            {
                "id": f"SR0-{index}",
                "polygon": _format_polygon(polygon),
                "covering": "undefined",
            },
        )
    ET.SubElement(
        surface_list,
        "Surface",
        {
            "id": "SF0-0",
            "polygon": _format_polygon(floor_points),
            "verticalOffset": "0",
        },
    )


def build_mxf(params: Any) -> bytes:
    """Generate a Layout MXF document (UTF-8 bytes) from ``DesignParameters``.

    Raises ``ValueError`` when ``floorPlanDimensions`` is missing, malformed,
    or non-positive.
    """
    width_mm, depth_mm = parse_dimensions(getattr(params, "floorPlanDimensions", None))
    width_m = width_mm / 1000.0
    depth_m = depth_mm / 1000.0
    _validate_plan(width_m, depth_m)

    specs = wall_specs(width_m, depth_m)
    batch_name = getattr(params, "buildingType", None) or "Building"

    roof_key = _resolve_roof_key(params)
    pitch_deg = _resolve_pitch(params)
    overhang_m = _resolve_overhang_m(params)
    roof_polygons = roof_surface_polygons(roof_key, width_m, depth_m, pitch_deg, overhang_m)
    floor_points = floor_surface_polygon(width_m, depth_m)

    root = ET.Element("Mxf")
    root.set("xmlns:xsd", XSD_NS)
    root.set("xmlns:xsi", XSI_NS)
    root.set("comment", MXF_COMMENT)
    root.set("originator", MXF_ORIGINATOR)
    root.set("version", MXF_VERSION)
    root.set("batchName", batch_name)
    root.set("batchDescription", batch_name)

    building_list = ET.SubElement(root, "BuildingList")
    building = ET.SubElement(
        building_list, "Building", {"job": batch_name, "name": batch_name}
    )
    _build_building_walls(building, specs)
    _build_walls(root, specs)
    _build_surfaces(root, building, floor_points, roof_polygons)
    _build_metadata(root, batch_name)

    raw = ET.tostring(root, encoding="utf-8")
    return minidom.parseString(raw).toprettyxml(indent="  ", encoding="utf-8")
